# Generated by Django 5.2.4 on 2025-12-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_in_validation',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_validation_code',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
    ]
