# Generated by Django 5.2.4 on 2025-12-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_id',
            field=models.CharField(blank=True, default='', help_text='Stripe customer ID', max_length=255),
            preserve_default=False,
        ),
    ]
