# Generated by Django 5.2.10 on 2026-04-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_account_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='platform_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
