#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

cd "${REPO_DIR}"

rm -f \
    ./Dockerfile.tmp \
    ./.dockerfile.build.* \
    ./.private_github_repos.build.* \
    ./.nocache.build.*
