#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_DIR="$(dirname "$SCRIPT_DIR")"
APP_REQUIREMENTS="$WEB_DIR/app_requirements.txt"
OUTPUT_FILE="$WEB_DIR/docker-compose.volumes.yml"

if [ ! -f "$APP_REQUIREMENTS" ]; then
    echo "Error: $APP_REQUIREMENTS not found"
    exit 1
fi

# Start building the output
cat > "$OUTPUT_FILE" << 'HEADER'
# AUTO-GENERATED FILE - Do not edit manually!
# Generated by: scripts/generate-dev-compose.sh
# To regenerate: ./scripts/generate-dev-compose.sh

# Dev overlay - mount app requirements for editable installs
# Usage: docker compose -f docker-compose.yml -f docker-compose.volumes.yml up

x-app-volumes: &app-volumes
HEADER

# Parse app_requirements.txt and generate volume mounts
while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines and comments
    [[ -z "$line" || "$line" =~ ^# ]] && continue

    # Extract package path (remove -e prefix if present)
    pkg_path="${line#-e }"
    pkg_path="${pkg_path## }"  # trim leading spaces

    # Get the package name from the path (last component)
    pkg_name=$(basename "$pkg_path")

    # Map /app/pkg-name to ../pkg-name for volume mount
    echo "  - ../$pkg_name:$pkg_path" >> "$OUTPUT_FILE"
done < "$APP_REQUIREMENTS"

# Add pip cache and rest of the file
cat >> "$OUTPUT_FILE" << 'FOOTER'
  - pip-cache:/home/appuser/.cache/pip

services:
  web:
    volumes: *app-volumes

  worker:
    volumes: *app-volumes

volumes:
  pip-cache:
FOOTER

echo "Generated $OUTPUT_FILE"
