# Generated by Django 5.2.4 on 2025-09-15 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_frontend_folder', models.CharField(blank=True, help_text='The S3 folder where frontend assets are stored', max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, default='prod_implementme', help_text='The Stripe Product ID for this site', max_length=255)),
                ('stripe_price_cents', models.IntegerField(default=2000, help_text='The price in cents for the Stripe subscription')),
                ('from_email', models.EmailField(default='team@my-app.openbase.app', help_text='Default from email address for this site', max_length=254)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='sites.site')),
            ],
            options={
                'verbose_name_plural': 'Site attributes',
            },
        ),
    ]
