# Generated by Django 5.2.10 on 2026-04-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_attributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteattributes',
            name='admin_app_labels',
            field=models.JSONField(blank=True, default=list, help_text='Django admin app labels visible for this site. Leave empty to show all apps.'),
        ),
    ]
