# Generated by Django 5.2.10 on 2026-04-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_attributes', '0002_siteattributes_admin_app_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteattributes',
            name='s3_custom_domain',
            field=models.CharField(blank=True, help_text="Optional CDN domain for this site's frontend assets. Defaults to AWS_S3_CUSTOM_DOMAIN.", max_length=255),
        ),
    ]
